services:
  doraemon:
    image: ghcr.io/sqing33/doraemon
    container_name: doraemon
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      # 持久化上传的文件
      - ./uploads:/app/doraemon-nodejs/public/images
      # 日志目录
      - ./logs:/app/logs
